TOTAL_UPTIME = 60 #min
TOTAL_PRODUCTION_TIME = 75 #min
TOTAL_PIECES = 30 #min
IDEAL_RUNRATE = 20
REJECTED_PIECES = 5

GOOD_PIECES = TOTAL_PIECES - REJECTED_PIECES

AVAILABILITY = TOTAL_UPTIME / TOTAL_PRODUCTION_TIME
PERFORMANCE = (TOTAL_PIECES / TOTAL_UPTIME) / IDEAL_RUNRATE
QUALITY = GOOD_PIECES / TOTAL_PIECES



OVERALL_OEE = (AVAILABILITY * PERFORMANCE * QUALITY)*100

print(OVERALL_OEE)